name: Security Scan & Dependency Updates

on:
  schedule:
    # Run weekly on Mondays
    - cron: '0 2 * * 1'
  push:
    branches: [ main, production ]
    paths:
      - '**/requirements.txt'
      - '**/package.json'
      - '**/package-lock.json'
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Scan Python dependencies
      uses: pyupio/safety-action@v1
      with:
        file: |
          frankenstein-db/requirements.txt
          ai-scraper-vm/requirements.txt
        api-key: ${{ secrets.SAFETY_API_KEY }}

    - name: Scan Node.js dependencies
      run: |
        cd ai-scraper-dashboard
        npm audit --audit-level high

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  dependency-updates:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Update Python dependencies
      uses: pyupio/pyup-action@v1
      with:
        requirements-files: |
          frankenstein-db/requirements.txt
          ai-scraper-vm/requirements.txt
        token: ${{ secrets.GH_PAT }}

    - name: Update Node.js dependencies
      run: |
        cd ai-scraper-dashboard
        npm update
        npm audit fix

    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_PAT }}
        commit-message: |
          🔄 Automated dependency updates

          - Updated Python dependencies
          - Updated Node.js dependencies
          - Fixed security vulnerabilities
        title: '🔄 Automated Dependency Updates'
        body: |
          ## 🤖 Automated Dependency Updates

          This PR contains automated updates for:
          - Python dependencies (frankenstein-db, ai-scraper-vm)
          - Node.js dependencies (ai-scraper-dashboard)
          - Security vulnerability fixes

          ### 🔍 Security Scan Results
          - [View Trivy scan results](${{ github.server_url }}/${{ github.repository }}/security/code-scanning)

          ### ✅ Checks Passed
          - Dependency vulnerability scan
          - Compatibility testing
          - Build verification
        branch: automated/dependency-updates
        delete-branch: true